### ISSUE TITLE
cryptopunks npm library?

### ISSUE THREAD

**Issue by shoma-ftv** [cryptopunksnotdead/programming-cryptopunks#1]
Is this something you are currently writing? Just wanting to understand if this is pseudocode or not.

Either way, it's great. Thanks!

**Comment by geraldb** [comment]
Please, post questions to the reddit - <https://www.reddit.com/r/cryptopunks> - the official support channel. Short answer - it is all working code using the (beginner friendly) ruby programming / scripting language.
