### ISSUE TITLE
Failure at 1st step... No such file or directory @ rb_sysopen - ./punks.png

### ISSUE THREAD

**Issue by Preachey** [cryptopunksnotdead/programming-cryptopunks#3]
Hey there, got no prior knowledge of Ruby. A noob pretty much. Calling 'require 'cryptopunks' ' on Interactive Ruby returns "true". Proceeding with reading 'punks.png' gives an error pasted below. What am I doing wrong? I tried copying the punks.png into gem lib but that didn't change anything.

Thanks!

irb(main):002:0> require 'cryptopunks'
pixelart/0.2.2 on Ruby 2.7.3 (2021-04-05) [x64-mingw32] in (C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pixelart-0.2.2)
cryptopunks/1.2.1 on Ruby 2.7.3 (2021-04-05) [x64-mingw32] in (C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cryptopunks-1.2.1)
=> true
irb(main):003:0> punks = Punks::Image::Composite.read( './punks.png' )
Traceback (most recent call last):
        7: from C:/Ruby27-x64/bin/irb.cmd:31:in `<main>'
        6: from C:/Ruby27-x64/bin/irb.cmd:31:in `load'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):3
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cryptopunks-1.2.1/lib/cryptopunks/composite.rb:13:in `read'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cryptopunks-1.2.1/lib/cryptopunks/composite.rb:13:in `open'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cryptopunks-1.2.1/lib/cryptopunks/composite.rb:13:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - ./punks.png)
irb(main):004:0>

**Comment by geraldb** [comment]
You are on your way. 

> No such file or directory @ rb_sysopen - ./punks.png

You need to download the punks.png composite image (by "hand") and save it in your working directory (./) - that is, the current directory you are in -  than try again. 

All the best. Cheers. Prost.

**Comment by Preachey** [comment]
Thank you for the reply!

I managed to get it working by adding the 'punks.png' to a project folder and then running the .rb file 👌
