### ISSUE TITLE
Trouble with require 'pixelart'

### ISSUE THREAD

**Issue by nicknovoa03** [cryptopunksnotdead/programming-cryptopunks#4]
How's it going? I have a similar question to the previous issue.

I am trying to run 'generate.rb' and I am getting this error.
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pixelart (LoadError)
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ./generate.rb:6:in `<main>'

On line 6, where the "require 'pixelart'" import is. I do not see a Pixelart class anywhere to be imported?
Am I missing something?

Thank you for your time!

**Comment by nicknovoa03** [comment]
> How's it going? I have a similar question to the previous issue.
> 
> I am trying to run 'generate.rb' and I am getting this error.
> internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- pixelart (LoadError) from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> from ./generate.rb:6:in `
> 
> '
> On line 6, where the "require 'pixelart'" import is. I do not see a Pixelart class anywhere to be imported?
> Am I missing something?
> 
> Thank you for your time!
I just had to install the packages. Thanks anyways!

**Comment by geraldb** [comment]
Please, post support questions to the public channel  @ <https://old.reddit.com/r/CryptoPunksDev/>  I try to help out over there. Thanks.
